import playwright from 'eslint-plugin-playwright';
import baseConfig from '../eslint.config.mjs';

export default [
  // Generated Playwright test output (gitignored, regenerated by every test
  // run) — never source code, must never be linted. Without this, a locally
  // present HTML trace-viewer report (which bundles third-party vendor JS
  // such as CodeMirror) gets walked by `eslint .` and fails with thousands
  // of unrelated errors on minified code.
  {
    ignores: ['test-results/**', 'playwright-report/**'],
  },
  playwright.configs['flat/recommended'],
  ...baseConfig,
  {
    files: ['**/*.ts', '**/*.js'],
    // Override or add rules here
    rules: {},
  },
];
