import * as XLSX from 'xlsx';
import { XlsxWorkbookBuilder, createWorkbookBuilder } from './xlsx-workbook.builder';
import { EXPORT_COLUMNS, ExportMeta, ExportRow } from './expense-export.types';

const meta: ExportMeta = {
  filter: { from: '2026-01-01', to: '2026-07-28', type: 'all', status: 'settled' },
  total: 2,
  exportedOn: new Date('2026-07-28T14:35:00Z'),
};

function row(over: Partial<ExportRow> = {}): ExportRow {
  return {
    id: 'e-1',
    expenseDate: '2026-07-01',
    createdAt: '2026-07-01T13:45:00.000Z',
    title: 'Groceries',
    description: 'weekly',
    amountTotal: 200,
    myShare: 100,
    currency: 'USD',
    category: 'Food & Drinks',
    expenseType: 'PERSONAL',
    groupName: null,
    paidByDisplayName: 'Alice',
    splitType: null,
    isSettled: false,
    status: 'posted',
    ...over,
  };
}

function parseSheet(buffer: ArrayBuffer, name: string): unknown[][] {
  const wb = XLSX.read(new Uint8Array(buffer), { type: 'array' });
  const ws = wb.Sheets[name];
  return XLSX.utils.sheet_to_json(ws, { header: 1, blankrows: false });
}

function parse(buffer: ArrayBuffer): unknown[][] {
  return parseSheet(buffer, 'Transactions');
}

function sheetNames(buffer: ArrayBuffer): string[] {
  return XLSX.read(new Uint8Array(buffer), { type: 'array' }).SheetNames;
}

describe('XlsxWorkbookBuilder', () => {
  const builder = new XlsxWorkbookBuilder();

  it('advertises the xlsx format and extension', () => {
    expect(builder.format).toBe('xlsx');
    expect(builder.extension).toBe('xlsx');
    expect(createWorkbookBuilder('xlsx')).toBeInstanceOf(XlsxWorkbookBuilder);
  });

  it('writes a Transactions and an Export Information sheet', () => {
    expect(sheetNames(builder.buildBuffer([row()], meta))).toEqual([
      'Transactions',
      'Export Information',
    ]);
  });

  it('writes a header row followed by one row per record', () => {
    const matrix = parse(
      builder.buildBuffer([row({ id: 'a' }), row({ id: 'b' })], meta),
    );

    expect(matrix[0]).toEqual(EXPORT_COLUMNS.map((c) => c.header));
    expect(matrix).toHaveLength(3); // header + 2 rows
    expect(matrix[1][1]).toBe('Groceries'); // Description column
  });

  it('produces a header-only sheet for an empty export', () => {
    const matrix = parse(builder.buildBuffer([], { ...meta, total: 0 }));

    expect(matrix).toHaveLength(1);
    expect(matrix[0]).toEqual(EXPORT_COLUMNS.map((c) => c.header));
  });

  it('keeps Amount and Your Share as numbers', () => {
    const matrix = parse(
      builder.buildBuffer([row({ amountTotal: 42.5, myShare: 21.25 })], meta),
    );

    const amountIdx = EXPORT_COLUMNS.findIndex((c) => c.header === 'Amount');
    const shareIdx = EXPORT_COLUMNS.findIndex((c) => c.header === 'Your Share');
    expect(matrix[1][amountIdx]).toBe(42.5);
    expect(matrix[1][shareIdx]).toBe(21.25);
  });

  it('renders export metadata on the Export Information sheet', () => {
    const info = parseSheet(
      builder.buildBuffer([row(), row()], meta),
      'Export Information',
    );
    const flat = new Map(
      info
        .filter((r) => r.length >= 2)
        .map((r) => [String(r[0]), r[1]]),
    );

    expect(info[0][0]).toBe('Export Information');
    expect(flat.get('Generated By')).toBe('FinMate');
    expect(flat.get('Exported On')).toBe('2026-07-28 14:35 UTC');
    expect(flat.get('From')).toBe('2026-01-01');
    expect(flat.get('To')).toBe('2026-07-28');
    expect(flat.get('Type')).toBe('All');
    expect(flat.get('Status')).toBe('Settled');
    expect(flat.get('Total Transactions')).toBe(2);
  });

  it('returns a blob with the spreadsheet mime type', () => {
    const blob = builder.build([row()], meta);
    expect(blob.type).toContain('spreadsheetml.sheet');
    expect(blob.size).toBeGreaterThan(0);
  });

  it('rejects unknown formats', () => {
    expect(() => createWorkbookBuilder('pdf' as never)).toThrow(
      /Unsupported export format/,
    );
  });
});
